### ISSUE TITLE
Hyperlinks

### ISSUE THREAD

**Issue by cyouh95** [KarlGoddard/TeaCozy#2]
You can use the `id` of each of the section of your page to help create hyperlinks to jump to each section:

```html
<a href="#top">Mission</a>
<a href="#mid">Featured Tea</a>
<a href="#btm">Locations</a>
```

https://github.com/KarlGoddard/TeaCozy/blob/master/index.html#L12-L14

**Comment by KarlGoddard** [comment]
Of course, thank you - I don't why I forgot to do that ... perhaps I just set the placeholders while I started building the body and forgot to return and update the links.
