### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [KarlGoddard/TeaCozy#5]
(Meets Expectations)

Nice job with this project! It looks like you have a solid understanding of how HTML and CSS work together for display of content. And keep up the great work on proper spacing, indentation, and commenting of your code.

One thing that's helpful to remember is that `id`s can be used not only as CSS selectors, but also for creating hyperlinks (#2). Here is a good resource on this: http://www.turnwall.com/articles/basic-styling-with-css-class-id/

As a further challenge, try creating your own page from scratch without the use of any specs or template. You definitely already have a good sense of how to organize and structure your code - this will be great practice for continuing to build your skills! Happy coding!

**Comment by KarlGoddard** [comment]
Thank you, I'm already working on some mock-ups of what I hope to attempt creating on completion of this course.
